name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy sur o2switch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
        version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build